; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_qspi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	gilmaimon/ArduinoWebsockets @ ^0.5.3
	fastled/FastLED @ ^3.6.0
	tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
	esphome/esp-micro-speech-features@^1.2.0
platform_packages = 
	toolchain-xtensa-esp32s3 @ file://C:/Users/nefedov_d/.platformio/packages/toolchain-xtensa-esp32s3
	toolchain-riscv32-esp @ file://C:/Users/nefedov_d/.platformio/packages/toolchain-riscv32-esp
	framework-arduinoespressif32 @ file://C:/Users/nefedov_d/.platformio/packages/framework-arduinoespressif32
